name: Trigger GCP build

env:
  GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
  BUILD_TRIGGER_SECRET: ${{ secrets.BUILD_TRIGGER_SECRET }}

on:
  push:
    branches:
      - "gcp-initial"
  workflow_dispatch: {}

jobs:
  trigger-build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/541264347167/locations/global/workloadIdentityPools/legend-engine-trigger-pool/providers/github-provider'
          service_account: 'legend-engine-trigger@ivan-legend-build-project.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        run: gcloud info

      - name: Print last build ID
        run: gcloud builds list --sort-by CREATE_TIME --limit 1 --format json | jq -r '.[0].id'

#      - name: Curl webhook
#        run: curl -X POST -H "application/json" "https://cloudbuild.googleapis.com/v1/projects/ivan-legend-build-project/triggers/parallel-legend-engine-build:webhook?key=${GCP_API_KEY}&secret=${BUILD_TRIGGER_SECRET}" -d "{}"

      - name: Build logs
        run: echo "Check for the build logs here https://console.cloud.google.com/storage/browser/legend-engine-logs"

